spring.application.name=ges_concours
spring.datasource.url=jdbc:postgresql://localhost:5432/ges_concours
spring.datasource.username=postgres
spring.datasource.password=passer

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB